### ISSUE TITLE
[Feature request] Hiding already reviewed files

### ISSUE THREAD

**Issue by DethAriel** [minhdam/BitbucketDiffTree#13]
It would be nice if there was a checkbox that allowed me to hide the files that I reviewed already from the tree view - that way reviewing PRs with 30+ files will become easier

**Comment by anupshah** [comment]
I like the idea; alternative suggestion: the tree control already has options to expand or collapse everything. Maybe an option to collapse all folders that are fully marked as reviewed, and an option to expand only those folders that are not fully reviewed?

**Comment by minhdam** [comment]
Good suggestion. I'm going to consider to implement it soon. Maybe a filtering function like Deth's idea.

Thank you Deth and Anup. I will let you know when it's done.

**Comment by minhdam** [comment]
Hi @DethAriel and @anupshah,

The **filtering files by reviewed, unreviewed and commented statuses** feature has been implemented in v1.7.

<img width="375" alt="screen shot 2018-07-29 at 3 17 22 pm" src="https://user-images.githubusercontent.com/20397125/43364373-1e75ce00-9343-11e8-90d6-9890c368f52e.png">

Please let me know if you have any issues.

Enjoy guys!
Cheers.

**Comment by anupshah** [comment]
Nice. Had a quick look and looks great. We've recently had very large PRs to look at, so need to wait for one of those to see if any other issues/suggestions. In the larger PRs I often find having all the folders available (but collapsed) easier to help navigate between files if I need to, but I'll try to use these toggles as is, because my worflow can probably adapt to this. Thanks!

**Comment by minhdam** [comment]
Lovely. Thanks for your feedback.
